server:
  port: 10010
spring:
  application:
    name: s-blockchain-grabber-eth-addliquadity
  profiles:
    include: blockchain-dev

swap:
  whale-addresses:
    - '0x84d34f4f83a87596cd3fb6887cff8f17bf5a7b83'
