spring:
  rabbitmq:
    host: 192.168.1.105
    port: 5672
    username: test
    password: Qwe456
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
        prefetch: 50
    virtual-host: token
    connection-timeout: 60000
