spring:
  profiles:
    include: core, core-dev, mongodb-dev, mail-dev

web3j:
  #  client-address: https://bsc-dataseed1.ninicoin.io/
  client-address: https://bsc-dataseed2.binance.org/
  #  client-address: https://data-seed-prebsc-1-s1.binance.org:8545
  admin-client: false


