spring:
  mail:
    host: smtp.126.com
    username: xxx@xxx.com
    password: MGCNDZCAMKCKRSTZ
    properties.mail.smtp.port: 994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

mail:
  remote:
    url: http://192.168.1.102:8080/
  custom:
    from: xxx@xxx.com
    to: xxx@xxx.com
    me: xxx@xxx.com

