server:
  port: 6544
spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      routes:

logging:
  config: classpath:logback.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6543/eureka/
