server:
  port: 80
spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 104857600 #100M
      routes:
        - id: b_command
          uri: lb://b-command
          order: 1
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1

        - id: b_command_websocket
          uri: lb://b-command-websocket
          order: 1
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1

logging:
  config: classpath:logback.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6543/eureka/
