spring:
  application:
    name: s-exchange-grabber-coinglass
  profiles:
    include: exchange, local
coinglass:
  url: https://open-api.coinglass.com/
  api:
    secret: 0fa0a6e0cac24eeaab1f712ac7c31df3
